### PR TITLE
Api overhaul - value transformations

### PR DESCRIPTION
**Pull request by frozeman**
Don't merge yet, i opened it already so that i can see the increased test coverage.

### CODE REVIEW

**Comment by kumavis** [comment]
Looking good! 
Standard callback signature is `cb(err, result)`. Do you think this is not appropriate for ethereum.js?
https://github.com/ethereum/ethereum.js/pull/79/files#diff-f9ee6b5f84e0ac1cde088e0cc86f045fR67

**Comment by frozeman** [comment]
i agree with the error first approach

**Comment by chevdor** [comment]
:clap:

**Comment by kumavis** [comment]
:fireworks: :+1:

**Pull request merged**
