### PR TITLE
Export same module name when building bundle

### LINKED ISSUE #34: why are we renaming the module when we build?
This is unnecessary and causes confusion. Should be the same as the name in package.json
see #14 #17

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #34

### CODE REVIEW

**Comment by kumavis** [comment]
Would also need to:
* update the readme
* bump major version in `package.json` as this would be a breaking change. However, thats only true for people consuming the built version who likely not be following semver, but whatever.

**Comment by kumavis** [comment]
related https://github.com/ethereum/ethereum.js/pull/56

**Comment by caktux** [comment]
Why is this still pending? Mergeable or not, this is a trivial fix and needs to be addressed.

**Comment by debris** [comment]
moved to #117

**Pull request closed without merging**
