### PR TITLE
Make browserify compatibile

### PR DESCRIPTION
**Pull request by dchambers**
This pull-request supersedes #116 (thanks for the feedback @debris).

### CODE REVIEW

**Comment by debris** [comment]
thanks :+1:

**Comment by dchambers** [comment]
Wow, that was a quick turn-around! I'm assuming there will also need to be some minor changes to the README.md to mention that you no longer need to separately include bignumber.js?

**Comment by debris** [comment]
Oh, yes... also updating examples would be cool ;)

**Comment by kumavis** [comment]
awesome! this is much better. whats the `.ignore('crypto')` part?

**Comment by dchambers** [comment]
Hey, @kumavis, it wasnt't obvious to me why @debris had done that either, but he actually already answered your question [over on this thread](https://github.com/ethereum/ethereum.js/pull/116#issuecomment-81515748).

**Pull request merged**
