### PR TITLE
added ethereumjs-utils

### PR DESCRIPTION
**Pull request by wanderer**
this seprates the utility functions to a sperate module that can be resused

### CODE REVIEW

**Comment by jorisbontje** [comment]
ethereum.js requires bignumber.js, ethereumjs-utils uses bignum; can those be unified?

**Comment by wanderer** [comment]
node-ethereum, ethereumjs-lib all use [bignum](https://github.com/justmoon/node-bignum) in node.js. When it get browserferied we use [bn.js](https://github.com/indutny/bn.js).  Also our elliptic curve operations relay on bn.js. So switching to a different bignumber.js is nontrival. How hard would it be to switch ethereum.js to bn.js ?

**Comment by wanderer** [comment]
so maybe I missing something but I can't actully see where bignumber.js is being used.

**Comment by debris** [comment]
I close, because it's outdated and it's not a priority right now.

**Pull request closed without merging**
