### PR TITLE
Switch to Karma

### PR DESCRIPTION
**Pull request by chevdor**
Disable for now few tests that fail until the switch to karma is done.
Replace mocha by Karma.

### CODE REVIEW

**Comment by debris** [comment]
i would like to have them both ;) please merge/rebase on latest master

**Comment by chevdor** [comment]
Sure, I am testing/discovering what you have done. Leave it to me until travis is a happy boy :smiley:

**Comment by chevdor** [comment]
I am actually quite curious if Safari/IE would pass... I doubt but let´s see.

**Comment by kumavis** [comment]
Who wants to take bets on OperaMini

**Comment by debris** [comment]
:+1:

**Comment by debris** [comment]
looks like you need to install chrome && firefox on test machine ;)

**Comment by debris** [comment]
this might be helpfull ;)
http://karma-runner.github.io/0.8/plus/Travis-CI.html

**Comment by chevdor** [comment]
The tests passed! Not sure if we need the extra complications :)
Don´t merge yet please, I am not done yet!

**Comment by debris** [comment]
haha, test passed, but look into travis output:
```
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [launcher]: Starting browser Firefox
ERROR [launcher]: Cannot start Chrome
	Can not find the binary google-chrome
	Please set env variable CHROME_BIN
ERROR [launcher]: Cannot start Firefox
	
INFO [launcher]: Trying to start Firefox again (1/2).
ERROR [launcher]: Cannot start Firefox
	
INFO [launcher]: Trying to start Firefox again (2/2).
ERROR [launcher]: Cannot start Firefox
	
ERROR [launcher]: Firefox failed 2 times (cannot start). Giving up.
```

**Comment by chevdor** [comment]
Hmm I admit, it could have been more glorious!

**Comment by kumavis** [comment]
>ERROR [launcher]: Firefox failed 2 times (cannot start). Giving up.

Travis! Hang in there! don't give up!

**Comment by chevdor** [comment]
Hmm I don´t find anything else than Firefox. I guess Opera, Chrome and Co will have to be ran manually.
I am adding node 0.12 but I remove Chrome in the default browsers. Although I leave it in the deps and I will add Opera.

**Comment by chevdor** [comment]
It looks like we can start playing finally :smile:
Having a break now. Merge it if you need it or leave it and I will try adding Opera to the game.

**Pull request merged**
